jwt.secret.key: "dsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsds"
spring:
  datasource:
    url: "jdbc:h2:file:./testdb"
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop